# Generated by Django 4.2.7 on 2023-11-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtail_ab_testing', '0001_squashed_0012_abtest_variant_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtest',
            name='variant_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.revision'),
        ),
    ]
