# Generated by Django 3.1.3 on 2020-11-03 17:03

import django.db.models.deletion
from django.db import migrations, models
from wagtail import VERSION as WAGTAIL_VERSION

if WAGTAIL_VERSION >= (8, 0):
    import swapper

    PAGE_MODEL_NAME = swapper.get_model_name("wagtailcore", "Page")
else:
    PAGE_MODEL_NAME = "wagtailcore.Page"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0052_pagelogentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=PAGE_MODEL_NAME,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(PAGE_MODEL_NAME,),
        ),
    ]
